### ISSUE TITLE
Getting python error when running maskgen.py

### ISSUE THREAD

**Issue by led5150** [iphelix/pack#20]
Hi, 

I created a .mask file from a small wordlist to test how this all works.  That part went fine and I got the following output.

*] Analyzing passwords in [previous_winners.txt]
[+] Analyzing 100% (87/87) of passwords
    NOTE: Statistics below is relative to the number of analyzed passwords, not total number of passwords

[*] Length:
[+]                         6: 32% (28)
[+]                         7: 11% (10)
[+]                         8: 11% (10)
[+]                         4: 10% (9)
[+]                         9: 10% (9)
[+]                         5: 06% (6)
[+]                        12: 05% (5)
[+]                        14: 03% (3)
[+]                        10: 02% (2)
[+]                        11: 02% (2)
[+]                        13: 02% (2)
[+]                        22: 01% (1)

[*] Character-set:
[+]                loweralpha: 24% (21)
etc .......

However, when then trying to use maskgen.py using this file with the following command:
python maskgen.py my_maskfile.mask

I get the following error:

Traceback (most recent call last):
  File "maskgen.py", line 272, in <module>
    maskgen.loadmasks(arg)
  File "maskgen.py", line 74, in loadmasks
    for (mask,occurrence) in maskReader:
ValueError: need more than 1 value to unpack

Any idea what is going wrong?  Thanks!!

**Comment by led5150** [comment]
Ah!  Never mind, I figured it out!  I was just piping the output to a file, and not using the -o option in statsgen.py.  It worked now!
